services:
  server:
    build:
      context: .
      dockerfile: ./tools/docker/server/Dockerfile
    stdin_open: true
    tty: true
    networks:
      usernet:
        ipv4_address: 10.5.0.5
      backend:
        ipv4_address: 11.0.0.4
    volumes:
      - type: bind
        source: ${PROJECT_ROOT_DIR}/out/server
        target: /test_bench/logs
  client1:
    build:
      context: .
      dockerfile: ./tools/docker/client/Dockerfile
    stdin_open: true
    tty: true
    networks:
      usernet:
        ipv4_address: 10.5.0.6
    volumes:
      - type: bind
        source: ${PROJECT_ROOT_DIR}/out/client1
        target: /test_bench/logs
  client2:
    build:
      context: .
      dockerfile: ./tools/docker/client/Dockerfile
    stdin_open: true
    tty: true
    networks:
      usernet:
        ipv4_address: 10.5.0.7
    volumes:
      - type: bind
        source: ${PROJECT_ROOT_DIR}/out/client2
        target: /test_bench/logs

networks:
  usernet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
  backend:
    name: "messenger_backend"
    external: true
